
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DesktopNavigation from "@/Components/Navigation/DesktopNavigation";
import { App } from "@/context/AppContext";
import { Cart } from "@/Components/Cart";
import { Favorite } from "@/Components/Favorite";
import { Menu } from "@/Components/Menu";

// TODO remove mock data
import { menuItems } from "@/helpers/mockData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <App>
      <html lang="en" dir='ltr'>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <DesktopNavigation />
          {children}
          
          <Menu items={menuItems} />
          <Cart />
          <Favorite />

        </body>
      </html>
    </App>
  );
}
