
import { Lora, Sofia_Sans } from "next/font/google";
import "./globals.css";
import DesktopNavigation from "@/Components/Navigation/DesktopNavigation";
import { AppProvider } from "@/context/AppContext";
import { Cart } from "@/Components/Cart";
import { Menu } from "@/Components/Menu";
import { Wishlist } from "@/Components/Wishlist";

// TODO remove mock data
import { menuItems } from "@/helpers/mockData";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { fetchSanity } from "@/sanity/fetch";
import { getLangDir } from "rtl-detect";

const lora = Lora({
  variable: "--font-secondary",
  subsets: ["cyrillic-ext"],
  weight: ["400", "500", "600", "700"],
});

const sofiaSans = Sofia_Sans({
  variable: "--font-primary",
  subsets: ["cyrillic-ext"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ params, children }) {
  const settings = await fetchSanity('settings')

  const { locale } = await params
  const direction = getLangDir(locale)

  return (
    <AppProvider initialSettings={settings} locale={locale} >
      <CartProvider>
        <WishlistProvider>
          <html lang={locale} dir={direction}>
            <body className={`${lora.variable} ${sofiaSans.variable} antialiased overflow-x-hidden cursor-default`}>
              <DesktopNavigation />

              <main className="p-6 laptop:p-12 desktop:px-24 max-w-full overflow-x-hidden">
                {children}
              </main>
              
              <Menu items={menuItems} />
              <Cart />
              <Wishlist />

            </body>
          </html>
        </WishlistProvider>
      </CartProvider>
    </AppProvider>
  );
}
